# Generated by Django 3.1.6 on 2021-02-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cancion',
        ),
        migrations.AddField(
            model_name='canciones',
            name='tags',
            field=models.ManyToManyField(to='musica.Tag'),
        ),
    ]
