# Generated by Django 3.1.6 on 2021-02-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='canciones',
            name='fecha',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='musica.canciones')),
            ],
        ),
        migrations.CreateModel(
            name='SubGenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenero', to='musica.canciones')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='musica.canciones')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genero', to='musica.canciones')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.banda')),
            ],
            options={
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.AddField(
            model_name='canciones',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musica.album'),
        ),
    ]
