# Generated by Django 3.1.6 on 2021-02-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20210217_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='cancion',
        ),
        migrations.RemoveField(
            model_name='subgenero',
            name='cancion',
        ),
        migrations.AddField(
            model_name='canciones',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musica.genero'),
        ),
        migrations.AddField(
            model_name='canciones',
            name='subgenero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musica.subgenero'),
        ),
    ]
