# Generated by Django 3.1.6 on 2021-02-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20210217_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='similares',
            field=models.ManyToManyField(blank=True, null=True, related_name='_banda_similares_+', to='musica.Banda'),
        ),
    ]
